image: reporter123/cmake:bionic

build:
  stage: build
  
  before_script: 
     - apt-get update && apt-get install -y extra-cmake-modules gettext qtbase5-dev extra-cmake-modules libkf5i18n-dev libkf5coreaddons-dev libkf5iconthemes-dev libkf5parts-dev libkf5doctools-dev libkf5crash-dev 
  script: 
    - cmake -DBUILD_TESTING=YES .
    - make
    - make install
  
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  #artifacts:
  #  paths:
  #    - mybinary
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    make ARGS="-V -E appstreamtest" test #exclude appstreamtest this does not run properly in my image
